name: lpm-publish-beta

on:
  release:
    types: [prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: echo ${steps.get_version.outputs.VERSION}
